### ISSUE TITLE
No style on heroku

### ISSUE THREAD

**Issue by Antiarchitect** [RSpace/spree-heroku#1]
I've just installed spree from sources on github (from master branch), installed heroku extension, removed spree gem from .gems to work from source. And when i try to open my app in browser I see that it works but without any css styling. What should I do?

**Comment by Antiarchitect** [comment]
Images and style serves by heroku only when I've commented some lines in .gitignore of the app:

```
#public/assets
#public/attachments
#public/blank_iframe.html
#public/images
#public/javascripts
#public/stylesheets
#public/ckeditora
```

added them and pushed to heroku - this works fine

**Comment by tylo** [comment]
Why do you think these were ignored to begin with then?

**Comment by Antiarchitect** [comment]
Cause this is the only/right way to get it work?

**Comment by tylo** [comment]
Oops. Sorry. I misinterpreted what you said.

**Comment by Antiarchitect** [comment]
Me too a little. I've supposed that my explaination of how to do the trick with Heroku (to track public folder in git for heroku) is the right or the only way to make it work.
