### ISSUE TITLE
Spree 0.11 & Heroku

### ISSUE THREAD

**Issue by andershaig** [RSpace/spree-heroku#2]
There's some initial conflicts from this code due to Spree going Rails 2.3.8 and one or two other versions. It got my Spree app running correctly just to change the versions in the gem manifest. I'm very very amateur at this point.

**Comment by hnprashanth** [comment]
Working gem manifest for me with Spree 0.11:

rails -v '2.3.8'
highline -v '1.5.1'
authlogic -v '>=2.1.3'
authlogic-oid -v '1.0.4'
activemerchant -v '1.5.1'
activerecord-tableless -v '0.1.0'
less -v '1.2.20'
stringex -v '1.0.3'
chronic -v '0.2.3'
whenever -v '0.3.7'
searchlogic -v '2.3.5'
will_paginate -v '2.3.11'
faker -v '0.3.1'
paperclip -v '>=2.3.1.1'
state_machine -v '0.8.0'
aws-s3 -v '>=0.6.2'
spree -v '0.11.0'

**Comment by will-s-owen** [comment]
Sorry for the resurrection, but for other people who are having to back rev.  I had to specify the version of hoe:

rails -v '2.3.8'
highline -v '1.5.1'
authlogic -v '>=2.1.2'
authlogic-oid -v '1.0.4'
activemerchant -v '1.5.1'
activerecord-tableless -v '0.1.0'
less -v '1.2.20'
stringex -v '1.0.3'
hoe -v '2.8.0'
chronic -v '0.3.0'
whenever -v '0.3.7'
searchlogic -v '2.3.5'
will_paginate -v '2.3.11'
faker -v '0.3.1'
paperclip -v '>=2.3.1.1'
state_machine -v '0.8.0'
aws-s3 -v '>=0.6.2'
spree -v '0.11.0'
